# Generated by Django 6.0.5 on 2026-08-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_user_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
